version: "3"
services:
  web:
    image: nginx
    ports:
      - 80:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api_gateway:
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    volumes:
      - ./api_gateway:/api_gateway
    ports:
      - 3000:3000
    depends_on:
      - mongo

  ms_influential_users_rails:
    build:
      context: .
      dockerfile: ./ms_influential_users_rails/Dockerfile
    volumes:
      - ./ms_influential_users_rails:/ms_influential_users_rails
    ports:
      - 3001:3000
    depends_on:
      - mongo

  ms_tagcloud_rails:
    build:
      context: .
      dockerfile: ./ms_tagcloud_rails/Dockerfile
    volumes:
      - ./ms_tagcloud_rails:/ms_tagcloud_rails
    ports:
      - 3002:3000
    depends_on:
      - mongo
